### ISSUE TITLE
Are there any papers that can be cited?

### ISSUE THREAD

**Issue by LeeVirtue** [tsurubee/banpei#13]
I want to use your method in the paper, are there any paper that can be cited, tks very much!

**Comment by tsurubee** [comment]
@LeeVirtue 
Thank you for using Banpei!
If you would like to cite `Singular spectrum transformation(sst)` implemented in banpei, here is the proposed paper for sst.
https://ide-research.net/papers/2005_SDM_Ide.pdf

If you would like to cite banpei as open source software, please cite it as follows.  
(The following is an example of Bibtex.)
```
@webpage{banpei,
  author   = "{H. Tsuruta}",
  title    = "{banpei}",
  url      = {https://github.com/tsurubee/banpei}
}
```
Thank you!
