### ISSUE TITLE
detect anomalies on sequential data

### ISSUE THREAD

**Issue by FeizNouri** [tsurubee/banpei#2]
Hi
i'm working on anomaly detection on energy consumption so i have a semi-sequential data. i tested the sst method and i don't think it works form me because it just detect a changing point, i tried to test the Hotelling method but i didn't understand how it works, can someone help me please.

**Comment by tsurubee** [comment]
Sorry for my late reply.
Hotelling method can be used like below.
```
import banpei 
model   = banpei.Hotelling()
results = model.detect(data, 0.01)  
```
The input 'data' must be one-dimensional array-like object containing a sequence of values.
The second argument '0.01' is threshold,  meaning that we judge that an event occurring at less than 1% is abnormal.

In general, hotelling theory is not suitable for detecting abnormality of time series data. It is suitable for outlier detection. And, it imposes a strong restriction that data follows a normal distribution.

I do not know what you want to do, but if you think that it is suitable for what you want to do, try using it.

**Comment by FeizNouri** [comment]
thanks very much for your reply.
