### ISSUE TITLE
Get the number positivity

### ISSUE THREAD

**Issue by lorenzolopez928** [tsurubee/banpei#5]
I have a rule that throws numbers between -50 and 50 randomly, is there any way to predict the sign (positive or negative) of the next release with at least 90% accuracy based on a historical record?

**Comment by tsurubee** [comment]
> numbers between -50 and 50 randomly

If the value are randomly generated, I think that you can predict the next value.  
Id data has some regularity, it may be possible to predict the following values.

**Comment by tsurubee** [comment]
Since your question is not directly related to the implementation of this repository, I close this Issue.
